/* Automatically generated by './build/bin/build-entry.ts' */

import AlAside from "packages/aside/index";
import AlButton from "packages/button/index";
import AlCol from "packages/col/index";
import AlContainer from "packages/container/index";
import AlDialog from "packages/dialog/index";
import AlFooter from "packages/footer/index";
import AlGrid from "packages/grid/index";
import AlHeader from "packages/header/index";
import AlMain from "packages/main/index";
import AlMessage from "packages/message/index";
import AlRow from "packages/row/index";
import AlSuperForm from "packages/super-form/index";
import AlTable from "packages/table/index";
import locale from "main/locale";
import AlCollapseTransition from "main/transitions/collapse-transition.js";

const components = [
  AlAside,
  AlButton,
  AlCol,
  AlContainer,
  AlFooter,
  AlGrid,
  AlHeader,
  AlMain,
  AlRow,
  AlSuperForm,
  AlTable,
  AlCollapseTransition
];

const install = function(vue: any, opts: any = {}) {
  locale.use(opts.locale);
  locale.i18n(opts.i18n);

  components.forEach((component: any) => {
    vue.component(component.name, component);
  });

  vue.prototype.$ALBATRO = {
    size: opts.size || "",
    zIndex: opts.zIndex || 2000
  };

  vue.prototype.$dialog = AlDialog;
  vue.prototype.$messages = AlMessage;
};

export default {
  version: "0.1.1",
  locale: locale.use,
  i18n: locale.i18n,
  install,
  AlCollapseTransition,
  AlAside,
  AlButton,
  AlCol,
  AlContainer,
  AlDialog,
  AlFooter,
  AlGrid,
  AlHeader,
  AlMain,
  AlMessage,
  AlRow,
  AlSuperForm,
  AlTable
  ////...components
};
