/* Automatically generated by './build/bin/build-entry.ts' */

import Vue from "vue";
import AlDialog from "packages/dialog/index";
import AlButton from "packages/button/index";
import AlTable from "packages/table/index";
import AlSuperForm from "packages/super-form/index";
import AlRow from "packages/row/index";
import AlCol from "packages/col/index";
import AlContainer from "packages/container/index";
import AlHeader from "packages/header/index";
import AlAside from "packages/aside/index";
import AlMain from "packages/main/index";
import AlFooter from "packages/footer/index";
import AlGrid from "packages/grid/index";
import AlMessage from "packages/message/index";
import locale from "main/locale";
import AlCollapseTransition from "main/transitions/collapse-transition.js";

const components = [
  AlButton,
  AlTable,
  AlSuperForm,
  AlRow,
  AlCol,
  AlContainer,
  AlHeader,
  AlAside,
  AlMain,
  AlFooter,
  AlGrid,
  AlCollapseTransition
];

const install = function(vue: any, opts: any = {}) {
  locale.use(opts.locale);
  locale.i18n(opts.i18n);

  components.forEach((component: any) => {
    Vue.component(component.name, component);
  });

  Vue.prototype.$ALBATRO = {
    size: opts.size || "",
    zIndex: opts.zIndex || 2000
  };

  Vue.prototype.$dialog = AlDialog;
  Vue.prototype.$message = AlMessage;
};

export default {
  version: "0.1.0",
  locale: locale.use,
  i18n: locale.i18n,
  install,
  AlCollapseTransition,
  ...components
};
